# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host_info',
            fields=[
                ('flag_id', models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u6807ID')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='\u8ba1\u7b97\u673a\u5168\u79f0')),
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='IP')),
                ('cpu', models.CharField(blank=True, max_length=100, verbose_name='CPU\u578b\u53f7')),
                ('men', models.CharField(blank=True, max_length=10, verbose_name='\u5185\u5b58')),
                ('disk', models.CharField(blank=True, max_length=10, verbose_name='\u786c\u76d8')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('group', models.CharField(blank=True, max_length=100, verbose_name='\u6240\u5c5e\u7ec4')),
                ('salt_status', models.BooleanField(default=False, verbose_name='Salt\u72b6\u6001')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='ssh_info',
            fields=[
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='\u8ba1\u7b97\u673a\u5168\u79f0')),
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='IP')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='\u5bc6\u7801')),
                ('port', models.CharField(blank=True, max_length=10, verbose_name='Port')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='\u5907\u6ce8')),
            ],
        ),
    ]
