# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20161024_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssh_info',
            name='server_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u6807ID'),
        ),
    ]
