# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_ssh_info_server_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='ip',
            field=models.CharField(blank=True, max_length=500, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='host_info',
            name='server_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='\u76ee\u6807ID'),
        ),
        migrations.AlterField(
            model_name='ssh_info',
            name='ip',
            field=models.CharField(blank=True, max_length=500, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='ssh_info',
            name='server_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='\u76ee\u6807ID'),
        ),
    ]
