# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items_info',
            fields=[
                ('items_id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('shell', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100, null=True)),
                ('port', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
