# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_info',
            name='server_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
