# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_info_server_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_info',
            name='host',
        ),
        migrations.RemoveField(
            model_name='items_info',
            name='name',
        ),
        migrations.RemoveField(
            model_name='items_info',
            name='path',
        ),
        migrations.RemoveField(
            model_name='items_info',
            name='process',
        ),
        migrations.RemoveField(
            model_name='items_info',
            name='shell',
        ),
        migrations.AddField(
            model_name='items_info',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u8ba1\u7b97\u673a\u5168\u79f0'),
        ),
        migrations.AddField(
            model_name='items_info',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u5e94\u7528\u5168\u79f0'),
        ),
        migrations.AddField(
            model_name='items_info',
            name='updata',
            field=models.CharField(blank=True, max_length=100, verbose_name='updata_shell'),
        ),
        migrations.AlterField(
            model_name='items_info',
            name='group',
            field=models.CharField(max_length=100, null=True, verbose_name='item_group'),
        ),
        migrations.AlterField(
            model_name='items_info',
            name='items_id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False, verbose_name='\u5e94\u7528ID'),
        ),
        migrations.AlterField(
            model_name='items_info',
            name='notes',
            field=models.CharField(max_length=100, null=True, verbose_name='item_notes'),
        ),
        migrations.AlterField(
            model_name='items_info',
            name='port',
            field=models.CharField(max_length=100, null=True, verbose_name='item_port'),
        ),
        migrations.AlterField(
            model_name='items_info',
            name='server_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u6807ID'),
        ),
        migrations.AlterField(
            model_name='items_info',
            name='service',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u5e94\u7528\u5168\u79f0'),
        ),
        migrations.AlterField(
            model_name='items_info',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='item_status'),
        ),
    ]
