# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20161025_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_info',
            name='server_id',
        ),
    ]
