# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20161104_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_info',
            name='port',
            field=models.CharField(max_length=50, null=True, verbose_name='item_port'),
        ),
    ]
