# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20161107_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_info',
            name='server_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u6807ID'),
        ),
    ]
