# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sys_logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
