name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set MySQL Server    
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        mysql version: 5.7
        mysql root passwotd: 123456
        mysql database: salt_ops
        mysql urser: salt_ops
        mysql password: 123456

    - name: Install Dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
